language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - android-25
    - build-tools-25.0.3
branches:
  except:
    - "/^[0-9]/"
script: ./ci/test.sh
notifications:
  email:
    recipients:
      - jorge.diazbenitosoriano@gmail.com
    on_success: change
    on_failure: always
